# Change these first
owner: volfclub # Your GitHub organization or username, where this repository lives
repo: travellings-upptime # The name of this repository

sites:
  - name: "开往"
    url: https://github.com/volfclub/travelling
  - name: "狼牌工作网址导航"
    url: https://www.volf.club
  - name: "音速装机"
    url: https://sonic.volf.club
  - name: "原谅糖"
    url: https://yltang.cn
  - name: "Barkure"
    url: https://guguga.cn
  - name: "Yamdr"
    url: https://www.yamdr.cn
  - name: "Arect和他的"
    url: https://www.kanofans.com
  - name: "Ryan Wang's Blog"
    url: https://ryanc.cc
  - name: "Seija"
    url: https://seija.me
  - name: "致远博客"
    url: https://blog.uniartisan.com
  - name: "JQM's Site"
    url: https://jinqimu.github.io
  - name: "CrownDaisy"
    url: https://crowndaisy.com
  - name: "殆己"
    url: https://heycmm.cn
  - name: "Legroft"
    url: https://jinjis.cn
  - name: "FANTASY"
    url: https://blog.tigerxly.com
  - name: "DIego's Blog"
    url: http://blog.diego.plus:5800
  - name: "果子小酱"
    url: https://sublimerui.top
  - name: "Sakura"
    url: https://cwxyr.me
  - name: "五叶魔法书"
    url: https://grimoire.cn
  - name: "风渐远"
    url: https://www.naraku.cn
  - name: "XiYo吧"
    url: https://www.xiyo8.cn
  - name: "锴"
    url: https://www.wangkai88.com
  - name: "Zeruns's Blog"
    url: https://blog.zeruns.tech
  - name: "Guqing's Blog"
    url: https://guqing.xyz
  - name: "非礼勿言"
    url: https://feiliwuyan.com
  - name: "星云C馆"
    url: https://www.m78.co
  - name: "Cheung"
    url: https://icheung.net
  - name: "雁陎的自耕地"
    url: https://www.sitstars.com
  - name: "阿猫阿狗"
    url: https://ionssource.cn
  - name: "风也温柔"
    url: https://blog.kaygb.com
  - name: "云游君的小站"
    url: https://www.yunyoujun.cn
  - name: "Eltrac's Track"
    url: https://blog.guhub.cn
  - name: "yuaneuro的博客"
    url: https://yuaneuro.cn
  - name: "krau'blog"
    url: https://krau.top
  - name: "Weifeng's Blog"
    url: https://wfblog.net
  - name: "ajian"
    url: https://blog.yegetables.cn
  - name: "freejishu的美丽世界"
    url: https://www.freejishu.com
  - name: "小太の游乐园"
    url: https://baka.fun
  - name: "Zhou‘s Blog"
    url: https://idream.ink
  - name: "地皮-DefiedParty"
    url: https://dpii.club
  - name: "CORE"
    url: https://core.moe
  - name: "Lin. 's Blog"
    url: https://www.lin03.cn
  - name: "TigerRoot"
    url: https://blog.tigerroot.cn
  - name: "蝶恋花"
    url: https://kylin.dev
  - name: "Pluveto"
    url: https://www.pluvet.com
  - name: "艺术长廊"
    url: https://www.6zgm.com
  - name: "Ojhdt's Blog"
    url: https://blog.ojhdt.com
  - name: "萌豚 Moechu"
    url: https://moechu.cn
  - name: "ncc的个人网站"
    url: https://www.zqcnc.cn
  - name: "刀客"
    url: https://blog.mboker.cn
  - name: "及时行乐"
    url: https://www.jsxlo.com
  - name: "iSwl's Blog"
    url: https://blog.iswl.vip
  - name: "顾盼の记事本"
    url: https://gupan.site
  - name: "爆胎的博客"
    url: https://www.itggg.cn
  - name: "花开陌上"
    url: https://moshanghua.net
  - name: "炎忍的博客"
    url: https://blog.imyan.ren
  - name: "青行三の个人博客"
    url: https://blog.jiehua1995.xyz
  - name: "有次博客"
    url: https://you.ci
  - name: "SkyWT"
    url: https://skywt.cn
  - name: "执手对影成双"
    url: https://www.lipk.org
  - name: "MySpace"
    url: https://www.zkl2333.com
  - name: "皮毛技术君"
    url: https://www.whoit.top
  - name: "Passer"
    url: https://takuron.top
  - name: "山葵酱"
    url: https://www.wasabi.fun
  - name: "Ying"
    url: https://blog.luvying.com
  - name: "风之暇想"
    url: https://www.fzxx.xyz
  - name: "今今今生"
    url: https://noheart.cn
  - name: "ADD-SP‘s Blog"
    url: https://www.addesp.com
  - name: "游轶的小站"
    url: https://blog.devyi.com
  - name: "MHuiG's Blog"
    url: https://blog.mhuig.top
  - name: "JalenChuh"
    url: https://blog.jalenchuh.cn
  - name: "LiuYun"
    url: https://blog.6yfz.cn
  - name: "Geek Era"
    url: https://www.geekera.cn
  - name: "Oo笑容太甜oO"
    url: https://kissbaofish.cn
  - name: "F君的博客"
    url: https://blog.fkun.tech
  - name: "Chr_小屋"
    url: https://blog.chrxw.com
  - name: "tabris的遥远星系"
    url: https://www.tabirstrees.top
  - name: "螓首蛾眉"
    url: https://jsun969.cn
  - name: "服务猿's 学习笔记"
    url: https://www.ishells.cn
  - name: "尼采般地抒情"
    url: https://www.wztlink1013.com
  - name: "Zkpeace"
    url: https://zkpeace.com
  - name: "Guang's blog"
    url: https://code016.com
  - name: "挨拍的儿"
    url: https://jimmyqin.cn
  - name: "Guyi’s Blog"
    url: https://www.y2jq.com
  - name: "七米蓝"
    url: https://www.chirmyram.top
  - name: "MZRME‘S"
    url: https://mzrme.com
  - name: "归舟棹远"
    url: https://www.tanknee.cn
  - name: "人家故里"
    url: https://fx7.top
  - name: "丁丁の店"
    url: https://blog.butanediol.me
  - name: "饿龙不是龙哩"
    url: https://loafing.cn
  - name: "低调阁"
    url: https://www.ddg.ink
  - name: "SWJ"
    url: https://blog.zggsong.cn
  - name: "Sanarous's Blog"
    url: https://bestzuo.cn
  - name: "HandSonic‘s Blog"
    url: https://handsonic.top
  - name: "Sorryfu"
    url: https://fushaolei.github.io
  - name: "TAOG's Blog"
    url: https://iktao.cn
  - name: "静かな森"
    url: https://innei.ren
  - name: "杜老师说"
    url: https://dusays.com
  - name: "独人欣赏"
    url: https://www.wangyusong.cn
  - name: "zcmimi's blog"
    url: https://blog.zcmimi.top
  - name: "TF的博客"
    url: https://blog.tengfei.website
  - name: "简兮小站"
    url: https://www.zk1220.com
  - name: "Colsrch'Blog"
    url: https://colsrch.cn
  - name: "AzuSemisa's Blog"
    url: https://azusemisa.top
  - name: "倚栏听风"
    url: https://www.yilantingfeng.site
  - name: "Xu's Blog"
    url: https://hasaik.com
  - name: "優萌初華"
    url: https://shoka.lostyu.me
  - name: "MES"
    url: https://rain.moimo.me
  - name: "ZigZagK的博客"
    url: https://zigzagk.top
  - name: "JsOnGmAX-博客"
    url: https://jsongx.com
  - name: "Kiritoghy's Blog"
    url: https://www.kiritoghy.cn
  - name: "BORBER"
    url: https://www.cnblogs.com/borber
  - name: "若非"
    url: https://loafing.cn
  - name: "不淡定的实验室"
    url: https://xd.sh.cn
  - name: "Micah"
    url: https://realmicah.xyz
  - name: "提莫酱的博客"
    url: https://www.timochan.cn
  - name: "COOL"
    url: https://www.coolku.cc
  - name: "夏日鱼塘"
    url: https://www.summerpond.cn
  - name: "异国迷宫的十字路口"
    url: https://blog.fivezha.cn
  - name: "可定博客"
    url: https://wnag.com.cn
  - name: "新漫猫"
    url: https://www.acg19.top
  - name: "Paddylin的博客"
    url: https://www.paddylin.top
  - name: "小孔成像"
    url: https://kurumit3.top
  - name: "Lime Network Blog"
    url: https://blog.limecho.net
  - name: "Panedioic's blog"
    url: https://blog.pppane.com
  - name: "大海的页面"
    url: https://ccccc.cyou
  - name: "56Kb/s"
    url: https://www.funix.cn
  - name: "林克的编程小记"
    url: https://www.codinglink.tech
  - name: "BD的小窝"
    url: https://www.bluesdawn.top
  - name: "LBTSTO自由商店"
    url: https://www.libertystore.one
  - name: "ChenYFanの博客"
    url: https://blog.cyfan.top
  - name: "江风引雨の小站"
    url: https://blog.luzy.top
  - name: "睿先森"
    url: https://senorui.top
  - name: "神州部落格"
    url: https://www.szfc13.cn
  - name: "Declan's Blog"
    url: https://blog.lihaojin.cn
  - name: "鲸一"
    url: https://www.saroin.com
  - name: "JaneWu's Blog"
    url: https://zhenwu99.gitee.io
  - name: "Johnson的博客"
    url: https://johnsonlee.site
  - name: "LeeBlog"
    url: https://www.leejean.top
  - name: "忆星辰"
    url: https://www.extingstudio.com
  - name: "YunShu'Blog"
    url: https://www.yunshu.site
  - name: "小康的个人主页"
    url: https://xiaokang.me
  - name: "威廉伯爵"
    url: https://megatontech.github.io
  - name: "hewith他和她"
    url: https://heshun.run
  - name: "Huiris's Log"
    url: https://huiris.com
  - name: "iVampireSP的物语"
    url: https://ivampiresp.com
  - name: "UTOPIA"
    url: https://ishya.top
  - name: "MBR的博客"
    url: https://blog.mbrjun.cn
  - name: "阿成儿Online"
    url: https://youdef.com
  - name: "黑石博客"
    url: https://www.heson10.com
  - name: "云帆沧海"
    url: https://yunfanch.com
  - name: "飞刀博客"
    url: https://www.feidaoboke.com
  - name: "优速VPSUR测评"
    url: https://vpsur.com
  - name: "野肆的生活分享"
    url: https://yexsi.com
  - name: "Juch 的导航"
    url: https://vmert.com
  - name: "Openwit启智"
    url: https://openwit.net
  - name: "The F Word"
    url: https://fiammanda.github.io
  - name: "Re Life"
    url: https://www.xiangshu233.cn
  - name: "qinxs小站"
    url: https://7bxing.com
  - name: "鱼跃此时海"
    url: https://www.overme.cn
  - name: "Vinking的小站"
    url: https://vinking.top
  - name: "MineCraft爱好者"
    url: https://www.mmcee.cn
  - name: "anonymous's blog"
    url: https://www.wenbin.org.cn
  - name: "阿方的博客"
    url: https://fang.blog.miri.site
  - name: "见字如面"
    url: https://hiwannz.com
  - name: "徐泽林的博客"
    url: https://www.zlinblog.cn
  - name: "RhythmLian's Blog"
    url: https://rhythmlian.cn
  - name: "alpaca++"
    url: https://alpaca.plus
  - name: "越行勤‘s Blog"
    url: https://yingwiki.top
  - name: "云生博客"
    url: https://qikaile.tk
  - name: "Funs Life"
    url: https://funs.life
  - name: "听得入迷空间"
    url: https://www.tdrme.cn
  - name: "hongCYu's Blog"
    url: https://hongcyu.cn
  - name: "nEo"
    url: https://neo00.top
  - name: "TomyJan的博客"
    url: https://blog.tomys.top
  - name: "一点快乐"
    url: https://www.yidiankuaile.com
  - name: "白日梦研究所"
    url: https://blog.angustar.com
  - name: "十二博客"
    url: https://blog.shiertx.com
  - name: "MoYi's Blog"
    url: https://blog.nekomoyi.com
  - name: "Troy & Chloe"
    url: https://www.yotroy.cool
  - name: "林中小屋"
    url: https://imszz.com
  - name: "Ender's Blog"
    url: https://ender.fun
  - name: "拾忆小站"
    url: https://www.syzhan.cn
  - name: "嚣张的灯塔"
    url: https://www.liuzhimin.vip
  - name: "W4J1e's blog"
    url: https://www.hin.cool
  - name: "轻风记"
    url: https://www.3328bk.cn
  - name: "Ganto的个人主页"
    url: https://www.ganto.cn
  - name: "Weidows の Nest"
    url: https://weidows.github.io
  - name: "Magma Ink"
    url: https://magma.ink
  - name: "幼稚园园长"
    url: https://yzyyz.top
  - name: "飞云师兄的主页"
    url: www.idasx.com
  - name: "Xecades's Blog"
    url: https://blog.xecades.xyz
  - name: "Amos‘blog"
    url: https://blog.amoswu.cn
  - name: "Mr_God's Note"
    url: https://www.mrgod.cn
  - name: "月光中的污点"
    url: https://www.extlight.com
  - name: "Sekiro's Blog"
    url: https://666wxy666.github.io
  - name: "Err0r"
    url: https://err0r.top
  - name: "余生 ' Blog"
    url: https://www.ysazw.cn
  - name: "墨染 の 博客"
    url: https://www.roaing.com
  - name: "萌！萝莉"
    url: https://loliloli.moe
  - name: "秉性之松"
    url: https://blog.iucky.cn
  - name: "7WATE`S Blog"
    url: https://blog.7wate.com
  - name: "吴李曾"
    url: https://www.wulinzeng.vip
  - name: "斯莫笔记"
    url: https://notes.zhangxiaocai.cn
  - name: "且听书吟"
    url: https://yufan.me
  - name: "Tony's blog"
    url: https://www.tonylsl.top
  - name: "科学ADV整合站"
    url: https://sciadv.mcseekeri.top
  - name: "御坂の地下室"
    url: https://misakaloli.com
  - name: "Steve Li's Blog"
    url: https://blog.stevelbr.top
  - name: "凌维三度"
    url: https://www.fwder.cn
  - name: "当神奇降临"
    url: https://blog.toutop.cn
  - name: "Hi,ghostsf"
    url: https://ghostsf.com
  - name: "小白 の 博客"
    url: https://www.xiaobai666.top
  - name: "MoLeft's Blog"
    url: https://www.moleft.cn
  - name: "Crash-Logs"
    url: https://crash-logs.cn
  - name: "空域"
    url: https://blog.moeworld.tech
  - name: "lzlz000"
    url: https://blog.lzlz.site
  - name: "Sakurai Kaede's Blog"
    url: https://sakurai.in
  - name: "Beelake's blog"
    url: https://beelake.github.io
  - name: "Caviar-X的博客"
    url: https://caviar-x.top
  - name: "不可方思"
    url: https://irr.ink
  - name: "Ljcbaby 的 网络小屋"
    url: https://blog.ljcbaby.top
  - name: "Caveolae - 乔治"
    url: https://www.flagg.cn
  - name: "爱极客"
    url: https://www.aigeek.top
  - name: "Fox Home"
    url: https://foolishfox.cn
  - name: "Jin Yuhan's Blog"
    url: https://jin-yuhan.github.io
  - name: "GOOPHER’s Blog"
    url: https://goopher.tk
  - name: "颢天图文"
    url: https://www.zouht.com
  - name: "水嗷博客"
    url: https://www.shuiao.top
  - name: "探索子"
    url: https://exploro.one
  - name: "Java_S"
    url: https://syjun.vip
  - name: "RS-Nocsi--博客论坛"
    url: https://www.rsnocsi.cn
  - name: "肥虫汽水摊"
    url: https://blog.bugcola.com/note
  - name: "Debug客栈"
    url: https://www.debuginn.cn
  - name: "Lin's Blog"
    url: https://linzeyin.github.io
  - name: "杰瑞日志"
    url: https://blog.jerryiweb.com
  - name: "Fadai's Blog"
    url: https://www.niuwx.cn
  - name: "帮开心"
    url: https://www.bangkaixin.com
  - name: "灰域行者的罐头盒"
    url: https://hacbox.me
  - name: "阈"
    url: https://www.limina.top
  - name: "E=mc²"
    url: https://lxh2006.tk
  - name: "Foxhole"
    url: https://blog.southfox.tk
  - name: "Hello! I’m 中二病晚期"
    url: https://imfurry.com
  - name: "萌新杰少の秘密基地"
    url: https://imcys.com
  - name: "希望的博客"
    url: https://xiwangly.top
  - name: "WishMeLz"
    url: https://blog.itsse.cn
  - name: "凝雀"
    url: https://blog.gatesx.cn
  - name: "新加卷的小宇宙"
    url: https://www.hzq.life
  - name: "CAYZLH"
    url: https://cayzlh.com
  - name: "咖里De"
    url: https://blog.garryde.com
  - name: "贼ㄨ船"
    url: https://blog.thiefship.com
  - name: "Eritque arcus's blog"
    url: https://eritque-arcus.tech
  - name: "kirito41dd's blog"
    url: https://www.kirito41dd.cn
  - name: "墨泽"
    url: https://blog.imzy.ink
  - name: "见字如晤"
    url: https://www.jianziruw.com
  - name: "繁星小站"
    url: https://www.moeor.com
  - name: "听闻"
    url: https://sangxuesheng.com
  - name: "南风的博客"
    url: https://www.nfxwblog.com
  - name: "沐の空间"
    url: https://muspace.top
  - name: "0.0个人博客"
    url: https://wangdabao.js.cool
  - name: "小毅博客"
    url: https://xeblog.cn
  - name: "膨胀的面包"
    url: https://blog.error.work
  - name: "演员UyoAhz"
    url: https://uyoahz.cn
  - name: "惜时如命"
    url: https://iamazing.cn
  - name: "zisu.dev"
    url: https://zisu.dev
  - name: "Revincx的小破站"
    url: https://blog.revincx.icu
  - name: "东方幻梦"
    url: https://blog.badapple.pro
  - name: "xuanzhi33的小站"
    url: https://www.xuanzhi33.cn
  - name: "Xzy® Homepage"
    url: https://xzy.one
  - name: "星路博客"
    url: https://www.ariels.xyz
  - name: "K'Blog"
    url: https://www.amazingk.cn
  - name: "阿苏可の小博客"
    url: https://asuko.icu
  - name: "Godapex"
    url: https://www.godapex.com
  - name: "GZTime's Blog"
    url: https://blog.gztime.cc
  - name: "TIR: Today I Read"
    url: https://tir.cool
  - name: "Sakura_Team"
    url: https://sakurasep.club
  - name: "HKK's Diary"
    url: https://ihkk.net
  - name: "BBing's Blog"
    url: https://bbing.com.cn
  - name: "雨临Lewis的博客"
    url: https://lewky.cn
  - name: "Cusalt!"
    url: https://cusalt.com
  - name: "雨中的博客"
    url: https://www.wenchong.space
  - name: "陈鑫磊的博客"
    url: https://www.cxl2020mc.top
  - name: "冻符「Minus-K」"
    url: https://www.kawashiros.club
  - name: "Laugh"
    url: https://blog.laugh12321.cn
  - name: "小理的小窝"
    url: https://xiaolii.com
  - name: "996 worker's ICU"
    url: https://www.996workers.icu
  - name: "Moyok的小屋"
    url: https://blog.moyok.xyz
  - name: "Hicool嗨酷"
    url: https://www.hicool.icu
  - name: "云梦 ╮不浅の部落阁"
    url: https://blog.adworld.top
  - name: "李本伟的博客"
    url: https://blog.libw.cc
  - name: "Po7mn1's Blog"
    url: https://blog.icecliffs.cn
  - name: "人人都是艺术家"
    url: https://here.sy
  - name: "求索日记"
    url: https://shuxhan.com
  - name: "Hey,Joker"
    url: https://jokerdig.com
  - name: "Morcat Blog"
    url: https://www.morcat.cn
  - name: "ldo's blog"
    url: https://ldo.one
  - name: "KatCloud"
    url: https://katcloud.cn
  - name: "温华的博客"
    url: https://wangquanguo.life
  - name: "进击的学霸的博客"
    url: https://blog.lovem.fun
  - name: "森木志"
    url: https://imxxz.cn
  - name: "Y7n05h 技术分享"
    url: https://blog.y7n05h.xyz
  - name: "晓果冻"
    url: https://www.chenmx.net
  - name: "若志随笔"
    url: https://www.rz.sb
  - name: "初 x 见"
    url: https://chuxjian.asia
  - name: "城北徐公"
    url: https://www.cbxg.icu
  - name: "二丫讲梵"
    url: https://wiki.eryajf.net
  - name: "liuliのsite"
    url: https://back2me.cn
  - name: "totoro & home"
    url: https://totoro.site
  - name: "Thun888"
    url: https://blog.thun888.xyz
  - name: "Sakitami的集装箱"
    url: https://blog.skihome.xyz
  - name: "CairBin's Blog"
    url: https://cairbin.top
  - name: "Savant's Blog"
    url: https://blog.lxscloud.top
  - name: "半闲"
    url: https://zhaobanxian.top
  - name: "沐瑾年"
    url: https://lemonx.cn
  - name: "逍遥隐士"
    url: https://cry33.com
  - name: "RSSBlog"
    url: https://rssblog.cn


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /travellings-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "travellings-upptime"
  introTitle: "**开往** 状态页 🔭"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: status
      href: /
    - title: issues
      href: https://github.com/volfclub/travellings-upptime/issues

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 5 * * *"