# Change these first
owner: volfclub # Your GitHub organization or username, where this repository lives
repo: travellings-upptime # The name of this repository

sites:
  - name: "0"
    url: https://github.com/volfclub/travelling
  - name: "1"
    url: https://www.volf.club
  - name: "2"
    url: https://sonic.volf.club
  - name: "3"
    url: https://yltang.cn
  - name: "4"
    url: https://guguga.cn
  - name: "6"
    url: https://www.yamdr.cn
  - name: "7"
    url: https://www.kanofans.com
  - name: "8"
    url: https://ryanc.cc
  - name: "9"
    url: https://seija.me
  - name: "10"
    url: https://blog.uniartisan.com
  - name: "11"
    url: https://jinqimu.github.io
  - name: "12"
    url: https://crowndaisy.com
  - name: "13"
    url: https://heycmm.cn
  - name: "15"
    url: https://jinjis.cn
  - name: "16"
    url: https://blog.tigerxly.com
  - name: "17"
    url: http://blog.diego.plus:5800
  - name: "18"
    url: https://sublimerui.top
  - name: "19"
    url: https://cwxyr.me
  - name: "22"
    url: https://grimoire.cn
  - name: "23"
    url: https://www.naraku.cn
  - name: "24"
    url: https://www.xiyo8.cn
  - name: "25"
    url: https://www.wangkai88.com
  - name: "26"
    url: https://blog.zeruns.tech
  - name: "27"
    url: https://guqing.xyz
  - name: "29"
    url: https://feiliwuyan.com
  - name: "30"
    url: https://www.m78.co
  - name: "31"
    url: https://icheung.net
  - name: "32"
    url: https://www.sitstars.com
  - name: "33"
    url: https://ionssource.cn
  - name: "35"
    url: https://blog.kaygb.com
  - name: "36"
    url: https://www.yunyoujun.cn
  - name: "38"
    url: https://blog.guhub.cn
  - name: "39"
    url: https://yuaneuro.cn
  - name: "41"
    url: https://krau.top
  - name: "42"
    url: https://wfblog.net
  - name: "45"
    url: https://blog.yegetables.cn
  - name: "46"
    url: https://www.freejishu.com
  - name: "47"
    url: https://baka.fun
  - name: "48"
    url: https://idream.ink
  - name: "49"
    url: https://dpii.club
  - name: "50"
    url: https://core.moe
  - name: "53"
    url: https://www.lin03.cn
  - name: "56"
    url: https://blog.tigerroot.cn
  - name: "57"
    url: https://kylin.dev
  - name: "59"
    url: https://www.pluvet.com
  - name: "61"
    url: https://www.6zgm.com
  - name: "64"
    url: https://blog.ojhdt.com
  - name: "65"
    url: https://moechu.cn
  - name: "66"
    url: https://www.zqcnc.cn
  - name: "67"
    url: https://blog.mboker.cn
  - name: "70"
    url: https://www.jsxlo.com
  - name: "71"
    url: https://blog.iswl.vip
  - name: "74"
    url: https://gupan.site
  - name: "75"
    url: https://www.itggg.cn
  - name: "76"
    url: https://moshanghua.net
  - name: "77"
    url: https://blog.imyan.ren
  - name: "78"
    url: https://blog.jiehua1995.xyz
  - name: "79"
    url: https://you.ci
  - name: "81"
    url: https://skywt.cn
  - name: "82"
    url: https://www.lipk.org
  - name: "83"
    url: https://www.zkl2333.com
  - name: "84"
    url: https://www.whoit.top
  - name: "85"
    url: https://takuron.top
  - name: "87"
    url: https://www.wasabi.fun
  - name: "88"
    url: https://blog.luvying.com
  - name: "89"
    url: https://www.fzxx.xyz
  - name: "90"
    url: https://noheart.cn
  - name: "91"
    url: https://www.addesp.com
  - name: "92"
    url: https://blog.devyi.com
  - name: "93"
    url: https://blog.mhuig.top
  - name: "94"
    url: https://blog.jalenchuh.cn
  - name: "95"
    url: https://blog.6yfz.cn
  - name: "96"
    url: https://www.geekera.cn
  - name: "98"
    url: https://kissbaofish.cn
  - name: "99"
    url: https://blog.fkun.tech
  - name: "101"
    url: https://blog.chrxw.com
  - name: "103"
    url: https://www.tabirstrees.top
  - name: "105"
    url: https://jsun969.cn
  - name: "106"
    url: https://www.ishells.cn
  - name: "107"
    url: https://www.wztlink1013.com
  - name: "108"
    url: https://zkpeace.com
  - name: "111"
    url: https://code016.com
  - name: "112"
    url: https://jimmyqin.cn
  - name: "116"
    url: https://www.y2jq.com
  - name: "117"
    url: https://www.chirmyram.top
  - name: "120"
    url: https://mzrme.com
  - name: "121"
    url: https://www.tanknee.cn
  - name: "122"
    url: https://fx7.top
  - name: "123"
    url: https://blog.butanediol.me
  - name: "124"
    url: https://loafing.cn
  - name: "125"
    url: https://www.ddg.ink
  - name: "126"
    url: https://blog.zggsong.cn
  - name: "127"
    url: https://bestzuo.cn
  - name: "128"
    url: https://handsonic.top
  - name: "130"
    url: https://fushaolei.github.io
  - name: "131"
    url: https://iktao.cn
  - name: "132"
    url: https://innei.ren
  - name: "133"
    url: https://dusays.com
  - name: "134"
    url: https://www.wangyusong.cn
  - name: "135"
    url: https://blog.zcmimi.top
  - name: "136"
    url: https://blog.tengfei.website
  - name: "137"
    url: https://www.zk1220.com
  - name: "139"
    url: https://colsrch.cn
  - name: "140"
    url: https://azusemisa.top
  - name: "142"
    url: https://www.yilantingfeng.site
  - name: "143"
    url: https://hasaik.com
  - name: "144"
    url: https://shoka.lostyu.me
  - name: "145"
    url: https://rain.moimo.me
  - name: "146"
    url: https://zigzagk.top
  - name: "147"
    url: https://jsongx.com
  - name: "148"
    url: https://www.kiritoghy.cn
  - name: "149"
    url: https://www.cnblogs.com/borber
  - name: "151"
    url: https://loafing.cn
  - name: "155"
    url: https://xd.sh.cn
  - name: "156"
    url: https://realmicah.xyz
  - name: "157"
    url: https://www.timochan.cn
  - name: "158"
    url: https://www.coolku.cc
  - name: "159"
    url: https://www.summerpond.cn
  - name: "160"
    url: https://blog.fivezha.cn
  - name: "162"
    url: https://wnag.com.cn
  - name: "163"
    url: https://www.acg19.top
  - name: "164"
    url: https://www.paddylin.top
  - name: "165"
    url: https://kurumit3.top
  - name: "166"
    url: https://blog.limecho.net
  - name: "167"
    url: https://blog.pppane.com
  - name: "171"
    url: https://ccccc.cyou
  - name: "172"
    url: https://www.funix.cn
  - name: "173"
    url: https://www.codinglink.tech
  - name: "174"
    url: https://www.bluesdawn.top
  - name: "175"
    url: https://www.libertystore.one
  - name: "176"
    url: https://blog.cyfan.top
  - name: "178"
    url: https://blog.luzy.top
  - name: "179"
    url: https://senorui.top
  - name: "180"
    url: https://www.szfc13.cn
  - name: "181"
    url: https://blog.lihaojin.cn
  - name: "182"
    url: https://www.saroin.com
  - name: "183"
    url: https://zhenwu99.gitee.io
  - name: "186"
    url: https://johnsonlee.site
  - name: "187"
    url: https://www.leejean.top
  - name: "189"
    url: https://www.extingstudio.com
  - name: "190"
    url: https://www.yunshu.site
  - name: "192"
    url: https://xiaokang.me
  - name: "193"
    url: https://megatontech.github.io
  - name: "194"
    url: https://heshun.run
  - name: "195"
    url: https://huiris.com
  - name: "196"
    url: https://ivampiresp.com
  - name: "197"
    url: https://ishya.top
  - name: "198"
    url: https://blog.mbrjun.cn
  - name: "200"
    url: https://youdef.com
  - name: "201"
    url: https://www.heson10.com
  - name: "202"
    url: https://yunfanch.com
  - name: "204"
    url: https://www.feidaoboke.com
  - name: "205"
    url: https://vpsur.com
  - name: "206"
    url: https://yexsi.com
  - name: "208"
    url: https://vmert.com
  - name: "209"
    url: https://openwit.net
  - name: "210"
    url: https://fiammanda.github.io
  - name: "211"
    url: https://www.xiangshu233.cn
  - name: "212"
    url: https://7bxing.com
  - name: "213"
    url: https://www.overme.cn
  - name: "214"
    url: https://vinking.top
  - name: "215"
    url: https://www.mmcee.cn
  - name: "216"
    url: https://www.wenbin.org.cn
  - name: "217"
    url: https://fang.blog.miri.site
  - name: "218"
    url: https://hiwannz.com
  - name: "219"
    url: https://www.zlinblog.cn
  - name: "220"
    url: https://rhythmlian.cn
  - name: "221"
    url: https://alpaca.plus
  - name: "222"
    url: https://yingwiki.top
  - name: "223"
    url: https://qikaile.tk
  - name: "224"
    url: https://funs.life
  - name: "225"
    url: https://www.tdrme.cn
  - name: "226"
    url: https://hongcyu.cn
  - name: "227"
    url: https://neo00.top
  - name: "229"
    url: https://blog.tomys.top
  - name: "230"
    url: https://www.yidiankuaile.com
  - name: "231"
    url: https://blog.angustar.com
  - name: "232"
    url: https://blog.shiertx.com
  - name: "233"
    url: https://blog.nekomoyi.com
  - name: "234"
    url: https://www.yotroy.cool
  - name: "236"
    url: https://imszz.com
  - name: "238"
    url: https://ender.fun
  - name: "239"
    url: https://www.syzhan.cn
  - name: "240"
    url: https://www.liuzhimin.vip
  - name: "241"
    url: https://www.hin.cool
  - name: "242"
    url: https://www.3328bk.cn
  - name: "243"
    url: https://www.ganto.cn
  - name: "244"
    url: https://weidows.github.io
  - name: "245"
    url: https://magma.ink
  - name: "246"
    url: https://yzyyz.top
  - name: "247"
    url: www.idasx.com
  - name: "248"
    url: https://blog.xecades.xyz
  - name: "249"
    url: https://blog.amoswu.cn
  - name: "250"
    url: https://www.mrgod.cn
  - name: "251"
    url: https://www.extlight.com
  - name: "252"
    url: https://666wxy666.github.io
  - name: "253"
    url: https://err0r.top
  - name: "254"
    url: https://www.ysazw.cn
  - name: "255"
    url: https://www.roaing.com
  - name: "256"
    url: https://loliloli.moe
  - name: "257"
    url: https://blog.iucky.cn
  - name: "258"
    url: https://blog.7wate.com
  - name: "259"
    url: https://www.wulinzeng.vip
  - name: "260"
    url: https://notes.zhangxiaocai.cn
  - name: "261"
    url: https://yufan.me
  - name: "262"
    url: https://www.tonylsl.top
  - name: "263"
    url: https://sciadv.mcseekeri.top
  - name: "264"
    url: https://misakaloli.com
  - name: "265"
    url: https://blog.stevelbr.top
  - name: "266"
    url: https://www.fwder.cn
  - name: "267"
    url: https://blog.toutop.cn
  - name: "268"
    url: https://ghostsf.com
  - name: "269"
    url: https://www.xiaobai666.top
  - name: "270"
    url: https://www.moleft.cn
  - name: "271"
    url: https://crash-logs.cn
  - name: "272"
    url: https://blog.moeworld.tech
  - name: "273"
    url: https://blog.lzlz.site
  - name: "274"
    url: https://sakurai.in
  - name: "275"
    url: https://beelake.github.io
  - name: "277"
    url: https://caviar-x.top
  - name: "278"
    url: https://irr.ink
  - name: "279"
    url: https://blog.ljcbaby.top
  - name: "280"
    url: https://www.flagg.cn
  - name: "281"
    url: https://www.aigeek.top
  - name: "282"
    url: https://foolishfox.cn
  - name: "283"
    url: https://jin-yuhan.github.io
  - name: "284"
    url: https://goopher.tk
  - name: "285"
    url: https://www.zouht.com
  - name: "286"
    url: https://www.shuiao.top
  - name: "287"
    url: https://exploro.one
  - name: "288"
    url: https://syjun.vip
  - name: "289"
    url: https://www.rsnocsi.cn
  - name: "290"
    url: https://blog.bugcola.com/note
  - name: "291"
    url: https://www.debuginn.cn
  - name: "292"
    url: https://linzeyin.github.io
  - name: "293"
    url: https://blog.jerryiweb.com
  - name: "294"
    url: https://www.niuwx.cn
  - name: "295"
    url: https://www.bangkaixin.com
  - name: "296"
    url: https://hacbox.me
  - name: "297"
    url: https://www.limina.top
  - name: "298"
    url: https://lxh2006.tk
  - name: "299"
    url: https://blog.southfox.tk
  - name: "300"
    url: https://imfurry.com
  - name: "301"
    url: https://imcys.com
  - name: "302"
    url: https://xiwangly.top
  - name: "303"
    url: https://blog.itsse.cn
  - name: "304"
    url: https://blog.gatesx.cn
  - name: "305"
    url: https://www.hzq.life
  - name: "306"
    url: https://cayzlh.com
  - name: "307"
    url: https://blog.garryde.com
  - name: "308"
    url: https://blog.thiefship.com
  - name: "309"
    url: https://eritque-arcus.tech
  - name: "310"
    url: https://www.kirito41dd.cn
  - name: "311"
    url: https://blog.imzy.ink
  - name: "312"
    url: https://www.jianziruw.com
  - name: "313"
    url: https://www.moeor.com
  - name: "314"
    url: https://sangxuesheng.com
  - name: "315"
    url: https://www.nfxwblog.com
  - name: "316"
    url: https://muspace.top
  - name: "317"
    url: https://wangdabao.js.cool
  - name: "318"
    url: https://xeblog.cn
  - name: "319"
    url: https://blog.error.work
  - name: "320"
    url: https://uyoahz.cn
  - name: "321"
    url: https://iamazing.cn
  - name: "322"
    url: https://zisu.dev
  - name: "323"
    url: https://blog.revincx.icu
  - name: "324"
    url: https://blog.badapple.pro
  - name: "325"
    url: https://www.xuanzhi33.cn
  - name: "326"
    url: https://xzy.one
  - name: "327"
    url: https://www.ariels.xyz
  - name: "328"
    url: https://www.amazingk.cn
  - name: "329"
    url: https://asuko.icu
  - name: "330"
    url: https://www.godapex.com
  - name: "331"
    url: https://blog.gztime.cc
  - name: "332"
    url: https://tir.cool
  - name: "333"
    url: https://sakurasep.club
  - name: "334"
    url: https://ihkk.net
  - name: "336"
    url: https://bbing.com.cn
  - name: "337"
    url: https://lewky.cn
  - name: "338"
    url: https://cusalt.com
  - name: "339"
    url: https://www.wenchong.space
  - name: "340"
    url: https://www.cxl2020mc.top
  - name: "341"
    url: https://www.kawashiros.club
  - name: "342"
    url: https://blog.laugh12321.cn
  - name: "343"
    url: https://xiaolii.com
  - name: "344"
    url: https://www.996workers.icu
  - name: "345"
    url: https://blog.moyok.xyz
  - name: "346"
    url: https://www.hicool.icu
  - name: "347"
    url: https://blog.adworld.top
  - name: "348"
    url: https://blog.libw.cc
  - name: "349"
    url: https://blog.icecliffs.cn
  - name: "350"
    url: https://here.sy
  - name: "351"
    url: https://shuxhan.com
  - name: "352"
    url: https://jokerdig.com
  - name: "353"
    url: https://www.morcat.cn
  - name: "354"
    url: https://ldo.one
  - name: "355"
    url: https://katcloud.cn
  - name: "356"
    url: https://wangquanguo.life
  - name: "357"
    url: https://blog.lovem.fun
  - name: "358"
    url: https://imxxz.cn
  - name: "359"
    url: https://blog.y7n05h.xyz
  - name: "360"
    url: https://www.chenmx.net
  - name: "361"
    url: https://www.rz.sb
  - name: "362"
    url: https://chuxjian.asia
  - name: "363"
    url: https://www.cbxg.icu
  - name: "364"
    url: https://wiki.eryajf.net
  - name: "365"
    url: https://back2me.cn
  - name: "366"
    url: https://totoro.site
  - name: "367"
    url: https://blog.thun888.xyz
  - name: "368"
    url: https://blog.skihome.xyz
  - name: "369"
    url: https://cairbin.top
  - name: "370"
    url: https://blog.lxscloud.top
  - name: "371"
    url: https://zhaobanxian.top
  - name: "372"
    url: https://lemonx.cn
  - name: "373"
    url: https://cry33.com
  - name: "374"
    url: https://rssblog.cn



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /travellings-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Travellings Status"
  introTitle: "**开往** 状态页 ♻️"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: status
      href: /
    - title: issues
      href: https://github.com/volfclub/travellings-upptime/issues
    - title: github
      href: https://github.com/volfclub/travellings

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "1 */9 * * *"